name: twitch_client
description: A package for developers to interact with the Twitch API easily, not all endpoints are implemented yet but they will eventually.
version: 0.0.9
homepage: https://github.com/livdroid/twitch_dart_api
repository: https://github.com/livdroid/twitch_dart_api

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  dio: ^5.1.1
  http_mock_adapter: ^0.4.2
  dartz: ^0.10.1
  web_socket_channel: ^2.4.0
  json_annotation: ^4.8.0
  freezed_annotation: ^2.2.0

dev_dependencies:
  flutter_lints: ^2.0.1
  mockito: ^5.4.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  freezed: ^2.3.2
  test: ^1.24.2