// Mocks generated by Mockito 5.3.2 from annotations
// in twitch_client/test/src/interface/twitch_interface_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:twitch_client/src/error/failure.dart' as _i5;
import 'package:twitch_client/src/interface/token_repository.dart' as _i3;
import 'package:twitch_client/src/props/token_client_props.dart' as _i6;
import 'package:twitch_client/src/response/validate_token_response.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TokenInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockTokenInterface extends _i1.Mock implements _i3.TokenInterface {
  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> revokeAccessToken(
          {required _i6.TokenClientProps? props}) =>
      (super.noSuchMethod(
        Invocation.method(
          #revokeAccessToken,
          [],
          {#props: props},
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
            _FakeEither_0<_i5.Failure, bool>(
          this,
          Invocation.method(
            #revokeAccessToken,
            [],
            {#props: props},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
                _FakeEither_0<_i5.Failure, bool>(
          this,
          Invocation.method(
            #revokeAccessToken,
            [],
            {#props: props},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, bool>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.ValidateTokenResponse>>
      verifyToken() => (super.noSuchMethod(
            Invocation.method(
              #verifyToken,
              [],
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure, _i7.ValidateTokenResponse>>.value(
                _FakeEither_0<_i5.Failure, _i7.ValidateTokenResponse>(
              this,
              Invocation.method(
                #verifyToken,
                [],
              ),
            )),
            returnValueForMissingStub: _i4.Future<
                    _i2.Either<_i5.Failure, _i7.ValidateTokenResponse>>.value(
                _FakeEither_0<_i5.Failure, _i7.ValidateTokenResponse>(
              this,
              Invocation.method(
                #verifyToken,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, _i7.ValidateTokenResponse>>);
}
